### ISSUE TITLE
ApiKey is now required for free version of currencyconverter

### ISSUE THREAD

**Issue by joffrey92** [TimothyYe/exchangerate#1]
Hi Timothy,

thanks for the great tool. Since a few days (I believe), each user of the free currency tool must register and get a personnalized key.

Could you add support for it ? 
Thanks in advance,
Joffrey

**Comment by TimothyYe** [comment]
Hi @joffrey92 , thank you for your feedback!

The new version V1.2 now supports API key, please refer to the [README](https://github.com/TimothyYe/exchangerate#get-api-key) and configure it.
Thanks!

The V1.2 release is here: [https://github.com/TimothyYe/exchangerate/releases/tag/V1.2](https://github.com/TimothyYe/exchangerate/releases/tag/V1.2)
